[tool.poetry]
name = "jupyter-poetry-env"
version = "0.1.0"
description = "for qiskit study"
authors = ["tax_free"]

[tool.poetry.dependencies]
python = "^3.11"
jupyterlab = "^3.0"
qiskit = "^1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
